version: 0.1
site_name: OCR Ingenieur Machine Learning
repo_name: oc-iml
repo_url: https://github.com/vjuge/oc-iml
site_description: "OpenClassRooms Ingenieur Machine Learning"
site_author: vju
site_url: 
site_dir: public
copyright: 'Copyright &copy; 2021 vjuge'
docs_dir: modules
dev_addr: '0.0.0.0:8080'


theme:
  name: material
  font:
    code: Roboto Mono

nav:
- Home: index.md
- Module P2:
  - 'P2/Readme.md'
  - 'P2/P2_01_loading_cleaning.ipynb'
  - 'P2/P2_02_Quanti.ipynb'
  - 'P2/P2_03_Quali.ipynb'
  - 'P2/P2_04_Analysis_Correlation.ipynb'
  - 'P2/P2_05_application.ipynb'
- Module P3:
  - 'P3/index.md'
  - 'P3/P3_01.ipynb'
  - 'P3/P3_02.ipynb'
- Module P4:
  - 'P4/index.md'
  - TP 1: 'P4/TP/01_Explorez_vos_données_avec_des_algorithmes_non_supervisés/index.md'

plugins:
  - search
  - mkdocs-jupyter :
      ignore_h1_titles: False
      ignore:  ["P2/input/*"]
      include: ["P2/*.ipynb", "P3/*.ipynb", "P4/*.ipynb"]
      include_source: True
  - exclude:
      glob:
        - P2/tmp/*
        - "*.csv"
        - "*.gzip"
      regex:
        - '.*\.(tmp|bin|tar)$'
