version: 0.1
site_name: OCR Ingenieur Machine Learning
repo_name: oc-iml
repo_url: https://github.com/vjuge/oc-iml
site_description: "OpenClassRooms Ingenieur Machine Learning"
site_author: vju
site_url: 
site_dir: public
copyright: 'Copyright &copy; 2021 vjuge'
docs_dir: modules
dev_addr: '0.0.0.0:8080'


theme:
  name: material
  font:
    code: Roboto Mono

nav:
- Home: index.md
- Module P2:
  - 'P2/Readme.md'
  - 'P2/P2_01_loading_cleaning.ipynb'
  - 'P2/P2_02_Quanti.ipynb'
  - 'P2/P2_03_Quali.ipynb'
  - 'P2/P2_04_Analysis_Correlation.ipynb'
  - 'P2/P2_05_application.ipynb'
- Module P3:
  - 'P3/index.md'
  - 'P3/P3_01.ipynb'
  - 'P3/P3_02.ipynb'
- Module P4:
  - 'P4/index.md'
  - 'P4/P4_01.ipynb'
  - TP 1: 'P4/TP/01_Explorez_vos_données_avec_des_algorithmes_non_supervisés/index.md'
- Module P5:
  - 'P5/index.md'
  - 'P5/notebook/module5.ipynb'
  - 'P5/notebook/data_process.ipynb'
- Module P6:
  - 'P6/index.md'
  - 'P6/module_P6_V3.ipynb'
- Module P7:
  - 'P7/index.md'
  - 'P7/gluonts.ipynb'
- Module P8:
  - 'P8/index.md'
  - 'P8/module-p8.ipynb'

plugins:
  - search
  - mkdocs-jupyter :
      ignore_h1_titles: False
      ignore:  ["P2/input/*", "P5/app/*", "P5/sample/*", "P5/TP/*", "P6/TP/*", "P6/examples/*"]
      include: ["P2/*.ipynb", "P3/*.ipynb", "P4/*.ipynb", "P5/notebook/*.ipynb", "P6/module_P6_V3.ipynb", "P7/gluonts.ipynb", "P8/module-p8.ipynb"]
      include_source: True
      kernel_name: python3
  - exclude:
      glob:
        - P2/tmp/*
        - "*.csv"
        - "*.gzip"
        - P5/app/*
        - P5/sample/*
        - P5/TP/*
        - P6/*.h5
        - P6/~/*
        - P6/examples/*
        - P6/mlruns/*
        - P6/TP
        - P8/data/*
      regex:
        - '.*\.(tmp|bin|tar)$'
